### ISSUE TITLE
"if len(bps) < 2" line

### ISSUE THREAD

**Issue by seva100** [otaheri/bps_torch#1]
Thank you for providing this code repository.
I am wondering if there is a typo in this line: https://github.com/otaheri/bps_torch/blob/22fc5c66fe7e3cd3c576548b878bf8c1bc16d007/bps_torch/bps.py#L130

I had to change it to `if len(bps.shape) < 2` to make it working.

**Comment by otaheri** [comment]
Thanks for your interest and reporting the bug. You are right, I will update the code.
